// Generated from bronze_monkey.h by tool/ffigen.dart.
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:retouched/bmlib/bronze_monkey.g.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Bool Function()>()
external bool bm_library_init();

@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Char>, ffi.UintPtr)>()
external int bm_get_last_error(ffi.Pointer<ffi.Char> buf, int len);

@ffi.Native<
  ffi.UintPtr Function(
    ffi.Uint8,
    ffi.Uint8,
    ffi.Uint16,
    ffi.Uint8,
    ffi.Uint8,
    ffi.Uint16,
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
  )
>()
external int bm_handshake_bytes(
  int cur_major,
  int cur_minor,
  int cur_build,
  int min_major,
  int min_minor,
  int min_build,
  ffi.Pointer<ffi.Uint8> out_ptr,
  int out_len,
);

@ffi.Native<ffi.UintPtr Function()>()
external int bm_registry_count();

@ffi.Native<ffi.Bool Function(ffi.Uint32)>()
external bool bm_registry_has(int id);

@ffi.Native<ffi.UintPtr Function(ffi.Pointer<ffi.Uint32>, ffi.UintPtr)>()
external int bm_registry_ids(ffi.Pointer<ffi.Uint32> out, int out_len);

@ffi.Native<ffi.UintPtr Function(ffi.Uint32)>()
external int bm_registry_name_len(int id);

@ffi.Native<
  ffi.UintPtr Function(ffi.Uint32, ffi.Pointer<ffi.Char>, ffi.UintPtr)
>()
external int bm_registry_name(int id, ffi.Pointer<ffi.Char> out, int out_len);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.UintPtr)>()
external void bm_buffer_free(ffi.Pointer<ffi.Uint8> ptr, int len);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_version_info(
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_generate_device_id(
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_generate_app_id(
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

@ffi.Native<ffi.Pointer<Engine> Function()>()
external ffi.Pointer<Engine> bm_engine_new();

@ffi.Native<ffi.Void Function(ffi.Pointer<Engine>)>()
external void bm_engine_free(ffi.Pointer<Engine> ptr_engine);

@ffi.Native<
  ffi.Bool Function(ffi.Pointer<Engine>, ffi.Pointer<ffi.Uint8>, ffi.UintPtr)
>()
external bool bm_engine_init_local_device(
  ffi.Pointer<Engine> ptr_engine,
  ffi.Pointer<ffi.Uint8> mp_ptr,
  int mp_len,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<Engine>,
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_engine_process_incoming(
  ffi.Pointer<Engine> ptr_engine,
  ffi.Pointer<ffi.Uint8> payload,
  int payload_len,
  ffi.Pointer<ffi.Uint8> arrival,
  int arrival_len,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

/// Tells the engine what time it is, in milliseconds on any monotonic clock
/// the caller prefers.
@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<Engine>,
    ffi.Uint64,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_engine_handle_time(
  ffi.Pointer<Engine> ptr_engine,
  int now_ms,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<Engine>,
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Uint64,
    ffi.Bool,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_engine_emit(
  ffi.Pointer<Engine> ptr_engine,
  ffi.Pointer<ffi.Uint8> cmd_ptr,
  int cmd_len,
  int now_ms,
  bool has_now,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<Engine>,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_engine_registry(
  ffi.Pointer<Engine> ptr_engine,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

/// Everyone waiting to be let in, for a caller that draws them rather than
/// answering the moment they arrive.
@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<Engine>,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_engine_pending_registrations(
  ffi.Pointer<Engine> ptr_engine,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

/// Applies a msgpack encoded EngineConfig: everything this engine is told about
/// itself, all at once.
@ffi.Native<
  ffi.Bool Function(ffi.Pointer<Engine>, ffi.Pointer<ffi.Uint8>, ffi.UintPtr)
>()
external bool bm_engine_configure(
  ffi.Pointer<Engine> ptr_engine,
  ffi.Pointer<ffi.Uint8> mp_ptr,
  int mp_len,
);

/// Takes a msgpack encoded list of handler names.
@ffi.Native<
  ffi.Bool Function(ffi.Pointer<Engine>, ffi.Pointer<ffi.Uint8>, ffi.UintPtr)
>()
external bool bm_engine_register_button_handlers(
  ffi.Pointer<Engine> ptr_engine,
  ffi.Pointer<ffi.Uint8> mp_ptr,
  int mp_len,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<Engine>)>()
external bool bm_engine_clear_button_handlers(ffi.Pointer<Engine> ptr_engine);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Uint8>, ffi.UintPtr)>()
external bool bm_engine_handshake(ffi.Pointer<ffi.Uint8> out_ptr, int out_len);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_controls_parse_xml(
  ffi.Pointer<ffi.Uint8> xml_ptr,
  int xml_len,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

@ffi.Native<ffi.Pointer<SchemeAssembler> Function()>()
external ffi.Pointer<SchemeAssembler> bm_scheme_assembler_new();

@ffi.Native<ffi.Void Function(ffi.Pointer<SchemeAssembler>)>()
external void bm_scheme_assembler_free(ffi.Pointer<SchemeAssembler> ptr);

/// Offers a completed chunk set. Returns 0 when the set is not a control scheme
/// (the caller owns the blob), 1 when consumed with nothing new, 2 when updated
/// (the merged scheme is written to out_scheme and out_initial is set), or -1 on
/// error.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<SchemeAssembler>,
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
    ffi.Pointer<ffi.Bool>,
  )
>()
external int bm_scheme_assembler_offer(
  ffi.Pointer<SchemeAssembler> ptr,
  ffi.Pointer<ffi.Uint8> set_id_ptr,
  int set_id_len,
  ffi.Pointer<ffi.Uint8> blob_ptr,
  int blob_len,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_scheme_ptr,
  ffi.Pointer<ffi.UintPtr> out_scheme_len,
  ffi.Pointer<ffi.Bool> out_initial,
);

/// Writes the current merged scheme to out and returns true, or returns false
/// when no scheme has been assembled yet.
@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<SchemeAssembler>,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_scheme_assembler_current(
  ffi.Pointer<SchemeAssembler> ptr,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<SchemeAssembler>)>()
external void bm_scheme_assembler_reset(ffi.Pointer<SchemeAssembler> ptr);

@ffi.Native<ffi.Bool Function(ffi.Int32, ffi.UintPtr)>()
external bool bm_log_configure(int level, int capacity);

@ffi.Native<ffi.Bool Function(ffi.Int32)>()
external bool bm_log_set_level(int level);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_log_take(
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

/// Reads a frame into a msgpack encoded WireView. Engine free: it allocates no
/// sequence numbers and needs no registered device, so it can run alongside a
/// live session without disturbing it.
@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_inspect_wire(
  ffi.Pointer<ffi.Uint8> data_ptr,
  int data_len,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

/// Serializes a msgpack encoded WireView into wire bytes.
@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_build_wire(
  ffi.Pointer<ffi.Uint8> view_ptr,
  int view_len,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

/// The longest message the library will accept, for callers that want to pass
/// it back to bm_framer_new rather than choose a limit of their own.
@ffi.Native<ffi.UintPtr Function()>()
external int bm_max_message_len();

/// Creates a framer that rejects messages longer than max_len. A limit above
/// the library ceiling is clamped to it.
@ffi.Native<ffi.Pointer<Framer> Function(ffi.UintPtr)>()
external ffi.Pointer<Framer> bm_framer_new(int max_len);

/// The limit this framer was created with.
@ffi.Native<ffi.UintPtr Function(ffi.Pointer<Framer>)>()
external int bm_framer_max_len(ffi.Pointer<Framer> ptr);

@ffi.Native<ffi.Void Function(ffi.Pointer<Framer>)>()
external void bm_framer_free(ffi.Pointer<Framer> ptr);

/// Feeds stream bytes and writes back every completed message, msgpack encoded
/// as an array of byte strings. Returns false when the stream is unusable.
@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<Framer>,
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_framer_feed(
  ffi.Pointer<Framer> ptr,
  ffi.Pointer<ffi.Uint8> data_ptr,
  int data_len,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<Framer>)>()
external void bm_framer_reset(ffi.Pointer<Framer> ptr);

/// Writes a message with the length prefix a stream transport needs.
@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_frame(
  ffi.Pointer<ffi.Uint8> data_ptr,
  int data_len,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

@ffi.Native<ffi.Pointer<Handshaker> Function(ffi.Int32)>()
external ffi.Pointer<Handshaker> bm_handshaker_new(int role);

@ffi.Native<
  ffi.Pointer<Handshaker> Function(
    ffi.Int32,
    ffi.Uint8,
    ffi.Uint8,
    ffi.Uint16,
    ffi.Uint8,
    ffi.Uint8,
    ffi.Uint16,
  )
>()
external ffi.Pointer<Handshaker> bm_handshaker_new_with_version(
  int role,
  int current_major,
  int current_minor,
  int current_build,
  int minimum_major,
  int minimum_minor,
  int minimum_build,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<Handshaker>)>()
external void bm_handshaker_free(ffi.Pointer<Handshaker> ptr);

/// Writes what to send now that the connection is up. An empty result means
/// there is nothing to send, which is the normal case for a responder.
@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<Handshaker>,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_handshaker_on_connect(
  ffi.Pointer<Handshaker> ptr,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

/// Classifies one message, writing back a msgpack encoded HandshakeOutcome.
@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<Handshaker>,
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_handshaker_on_message(
  ffi.Pointer<Handshaker> ptr,
  ffi.Pointer<ffi.Uint8> data_ptr,
  int data_len,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<Handshaker>)>()
external bool bm_handshaker_is_complete(ffi.Pointer<Handshaker> ptr);

@ffi.Native<ffi.Void Function(ffi.Pointer<Handshaker>)>()
external void bm_handshaker_reset(ffi.Pointer<Handshaker> ptr);

/// Whether these bytes open a cross domain policy request.
@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Uint8>, ffi.UintPtr)>()
external bool bm_is_policy_request(
  ffi.Pointer<ffi.Uint8> data_ptr,
  int data_len,
);

/// Writes the policy response to send back, NUL terminator included.
@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_policy_response(
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

/// Creates a sniffer that watches the head of one connection for a policy
/// request, for transports that hand over bytes rather than let them be peeked.
@ffi.Native<ffi.Pointer<Sniffer> Function()>()
external ffi.Pointer<Sniffer> bm_policy_sniffer_new();

@ffi.Native<ffi.Void Function(ffi.Pointer<Sniffer>)>()
external void bm_policy_sniffer_free(ffi.Pointer<Sniffer> ptr);

/// Offers the next bytes off the wire, writing back a msgpack encoded Sniff.
@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<Sniffer>,
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external bool bm_policy_sniffer_feed(
  ffi.Pointer<Sniffer> ptr,
  ffi.Pointer<ffi.Uint8> data_ptr,
  int data_len,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
  ffi.Pointer<ffi.UintPtr> out_len,
);

/// Whether the answer is still open. Once it is not, bytes can go straight on.
@ffi.Native<ffi.Bool Function(ffi.Pointer<Sniffer>)>()
external bool bm_policy_sniffer_is_watching(ffi.Pointer<Sniffer> ptr);

/// Whether the connection that just dropped was one we hung up on after
/// answering. Watches again either way.
@ffi.Native<ffi.Bool Function(ffi.Pointer<Sniffer>)>()
external bool bm_policy_sniffer_hung_up(ffi.Pointer<Sniffer> ptr);

@ffi.Native<ffi.Void Function(ffi.Pointer<Sniffer>)>()
external void bm_policy_sniffer_reset(ffi.Pointer<Sniffer> ptr);

enum DeviceType {
  Any(0),
  Unity(1),
  IPhone(2),
  Flash(3),
  Android(4),
  Native(5),
  Palm(6),
  Server(7);

  final int value;
  const DeviceType(this.value);

  static DeviceType fromValue(int value) => switch (value) {
    0 => Any,
    1 => Unity,
    2 => IPhone,
    3 => Flash,
    4 => Android,
    5 => Native,
    6 => Palm,
    7 => Server,
    _ => throw ArgumentError('Unknown value for DeviceType: $value'),
  };
}

enum PacketType {
  Data(0),
  Ping(1),
  Ack(2),
  Echo(3),
  Analysis(4),
  KeepAlive(5);

  final int value;
  const PacketType(this.value);

  static PacketType fromValue(int value) => switch (value) {
    0 => Data,
    1 => Ping,
    2 => Ack,
    3 => Echo,
    4 => Analysis,
    5 => KeepAlive,
    _ => throw ArgumentError('Unknown value for PacketType: $value'),
  };
}

enum EndpointMode {
  Game(1),
  Controller(2);

  final int value;
  const EndpointMode(this.value);

  static EndpointMode fromValue(int value) => switch (value) {
    1 => Game,
    2 => Controller,
    _ => throw ArgumentError('Unknown value for EndpointMode: $value'),
  };
}

enum TouchState {
  Began(1),
  Moved(2),
  Stationary(3),
  Ended(4),
  Cancelled(5);

  final int value;
  const TouchState(this.value);

  static TouchState fromValue(int value) => switch (value) {
    1 => Began,
    2 => Moved,
    3 => Stationary,
    4 => Ended,
    5 => Cancelled,
    _ => throw ArgumentError('Unknown value for TouchState: $value'),
  };
}

enum ControlMode {
  Game(0),
  Text(1),
  Nav(2),
  Wait(3);

  final int value;
  const ControlMode(this.value);

  static ControlMode fromValue(int value) => switch (value) {
    0 => Game,
    1 => Text,
    2 => Nav,
    3 => Wait,
    _ => throw ArgumentError('Unknown value for ControlMode: $value'),
  };
}

enum ChannelType {
  Broadcast(0),
  Acceleration(1),
  Touch(2),
  Message(3),
  String(4),
  Bytes(5),
  Gyro(6),
  Orientation(7),
  DPad(8);

  final int value;
  const ChannelType(this.value);

  static ChannelType fromValue(int value) => switch (value) {
    0 => Broadcast,
    1 => Acceleration,
    2 => Touch,
    3 => Message,
    4 => String,
    5 => Bytes,
    6 => Gyro,
    7 => Orientation,
    8 => DPad,
    _ => throw ArgumentError('Unknown value for ChannelType: $value'),
  };
}

enum BMReliability {
  Unreliable(0),
  ReliableUnordered(1),
  ReliableOrdered(2);

  final int value;
  const BMReliability(this.value);

  static BMReliability fromValue(int value) => switch (value) {
    0 => Unreliable,
    1 => ReliableUnordered,
    2 => ReliableOrdered,
    _ => throw ArgumentError('Unknown value for BMReliability: $value'),
  };
}

/// Which side of a connection speaks first.
enum LinkRole {
  Initiator(0),
  Responder(1);

  final int value;
  const LinkRole(this.value);

  static LinkRole fromValue(int value) => switch (value) {
    0 => Initiator,
    1 => Responder,
    _ => throw ArgumentError('Unknown value for LinkRole: $value'),
  };
}

enum LogLevel {
  Error(1),
  Warn(2),
  Info(3),
  Debug(4),
  Trace(5);

  final int value;
  const LogLevel(this.value);

  static LogLevel fromValue(int value) => switch (value) {
    1 => Error,
    2 => Warn,
    3 => Info,
    4 => Debug,
    5 => Trace,
    _ => throw ArgumentError('Unknown value for LogLevel: $value'),
  };
}

enum Sensor {
  Touch(0),
  Accel(1),
  Gyro(2),
  Orientation(3);

  final int value;
  const Sensor(this.value);

  static Sensor fromValue(int value) => switch (value) {
    0 => Touch,
    1 => Accel,
    2 => Gyro,
    3 => Orientation,
    _ => throw ArgumentError('Unknown value for Sensor: $value'),
  };
}

enum TouchPhase {
  Began(1),
  Moved(2),
  Ended(4),
  Cancelled(5);

  final int value;
  const TouchPhase(this.value);

  static TouchPhase fromValue(int value) => switch (value) {
    1 => Began,
    2 => Moved,
    4 => Ended,
    5 => Cancelled,
    _ => throw ArgumentError('Unknown value for TouchPhase: $value'),
  };
}

enum VersionCheck {
  Compatible(0),
  LocalTooOld(1),
  RemoteTooOld(2);

  final int value;
  const VersionCheck(this.value);

  static VersionCheck fromValue(int value) => switch (value) {
    0 => Compatible,
    1 => LocalTooOld,
    2 => RemoteTooOld,
    _ => throw ArgumentError('Unknown value for VersionCheck: $value'),
  };
}

final class Engine extends ffi.Opaque {}

final class Framer extends ffi.Opaque {}

final class Handshaker extends ffi.Opaque {}

final class SchemeAssembler extends ffi.Opaque {}

final class Sniffer extends ffi.Opaque {}
